receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  debug:
    verbosity: detailed

  prometheus:
    endpoint: "${PROMETHEUS_ENDPOINT:-0.0.0.0:8889}"
    const_labels:
      label1: "${LABEL1:-value1}"

  logging:

  zipkin:
    endpoint: "${ZIPKIN_ENDPOINT:-http://zipkin.railway.internal:9411/api/v2/spans}"
    format: proto

  otlp/jaeger:
    endpoint: "${JAEGER_ENDPOINT:-jaeger.railway.internal:4317}"
    tls:
      insecure: "${JAeger_TLS_INSECURE:-true}"

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: "${PPROF_ENDPOINT:-1888}"
  zpages:
    endpoint: "${ZPAGES_ENDPOINT:-55679}"

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, zipkin, otlp/jaeger, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus, debug]